### ISSUE TITLE
Using with Webpack

### ISSUE THREAD

**Issue by Velua** [arjunkomath/node-freshdesk-api#43]
Just a quick question, has anyone had any trouble using this package with webpack in use as well?

**Comment by Velua** [comment]
Can close cuz this questions super ambiguous

**Comment by maxkoryukov** [comment]
Probably, there shouldn't be any issues caused by any transpiler/packer. But need to check, whether Freshdesk itself allows cross-origin requests (CORS). 

If CORS is forbidden on Freshdesk, then it is not possible to use this package from a browser (probably). 

If CORS is allowed, we could try to check the following popular tools for compatibility:

- [ ] webpack
- [ ] browserify
- [ ] babel (with any of *next* configs)
- [ ] ??? something more?

The best approach - write simple tests, or create a simple web-page to use

**Comment by Velua** [comment]
Solved!

Was able to fix by adding this in my webpack config...
Freshdesk does support CORS. 

webpackConfig.node = { 
  console: true,
  fs: 'empty',
  net: 'empty',
  tls: 'empty'
}

**Comment by maxkoryukov** [comment]
@Velua , added to readme. for now - without any changes

https://github.com/arjunkomath/node-freshdesk-api#use-with-webpack
